In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('2006_2017_features.csv')

In [3]:
df.loc[:,'date'] = pd.to_datetime(df['date'])

In [4]:
df.set_index('date', inplace=True)

In [5]:
df['day'] = df.index.day

In [6]:
df.shape

(1827, 15)

In [7]:
df.reset_index(inplace=True)

In [8]:
df.head(15)

date  year  index  N1  N2  N3  N4  N5  N6  S1  color   zodiac   EvO  \
0  2006-01-03  2006      1  25  17  38  26  23  24  47   blue      rat   odd   
1  2006-01-05  2006      2  10  22  46  44   5  38  13    red      dog   odd   
2  2006-01-08  2006      3  38  26  28  42  10   1  43  green   dragon   odd   
3  2006-01-10  2006      4  38  39  21  25  36   5   4   blue     goat  even   
4  2006-01-12  2006      5  15  37  36  24  27  25  35    red      rat   odd   
5  2006-01-14  2006      6  19  34   1  12  29  32  46    red       ox  even   
6  2006-01-17  2006      7  13  47  11  25  29  38  12    red      pig  even   
7  2006-01-19  2006      8  28  24  26  44  31  47  17  green    horse   odd   
8  2006-01-21  2006      9  20   1   7  45  40  34  22  green       ox  even   
9  2006-01-24  2006     10  28  35   6  33  31  14  26   blue  rooster  even   
10 2006-01-26  2006     11  18  22  27  28  43  23  35    red      rat   odd   
11 2006-01-28  2006     12  41  27  30  16  22  39  40    red     goat  even   
12 2006-01-30  2006     13  21  48  35   9  33  22  43  green   dragon   odd   
13 2006-02-02  2006     14  37  20   4  23   5   3  38  green  rooster  even   
14 2006-02-04  2006     15  41  39  40  34  45  19  23    red      rat   odd   

       BS  month  day  
0     big      1    3  
1   small      1    5  
2     big      1    8  
3   small      1   10  
4     big      1   12  
5     big      1   14  
6   small      1   17  
7   small      1   19  
8   small      1   21  
9     big      1   24  
10    big      1   26  
11    big      1   28  
12    big      1   30  
13    big      2    2  
14  small      2    4

In [9]:
# cumulative number in the past 10 years
blue = []
red = []
green = []
for i in range(1,1828):
    blue.append(df['color'].iloc[:i].value_counts()['blue'])
    
for i in range(2,1828):
    red.append(df['color'].iloc[:i].value_counts()['red'])
    
for i in range(3,1828):
    green.append(df['color'].iloc[:i].value_counts()['green'])

blue = [0] + blue
red = [0,0] + red
green = [0,0,0] + green

In [10]:
df['red'] = red[0:1827]
df['green'] = green[0:1827]
df['blue'] = blue[0:1827]

In [19]:
df.head()

date  year  index  N1  N2  N3  N4  N5  N6  S1  color  zodiac   EvO  \
0 2006-01-03  2006      1  25  17  38  26  23  24  47   blue     rat   odd   
1 2006-01-05  2006      2  10  22  46  44   5  38  13    red     dog   odd   
2 2006-01-08  2006      3  38  26  28  42  10   1  43  green  dragon   odd   
3 2006-01-10  2006      4  38  39  21  25  36   5   4   blue    goat  even   
4 2006-01-12  2006      5  15  37  36  24  27  25  35    red     rat   odd   

      BS  month  day  red  green  blue  
0    big      1    3    0      0     0  
1  small      1    5    0      0     1  
2    big      1    8    1      0     1  
3  small      1   10    1      1     1  
4    big      1   12    1      1     2

In [42]:
# cumulative number in the past month
blue_26 = []
red_26 = []
green_26 = []

for i in range(26,1828):
    blue_26.append(df['color'].iloc[i-25:i].value_counts()['blue'])

for i in range(26,1828):
    red_26.append(df['color'].iloc[i-25:i].value_counts()['red'])
    
for i in range(26,1828):
    green_26.append(df['color'].iloc[i-25:i].value_counts()['green'])

blue_26 = [0]*26 + blue_26
red_26 = [0]*26 + red_26
green_26 = [0]*26 + green_26

In [46]:
df['red_26'] = red_26[0:1827]
df['green_26'] = green_26[0:1827]
df['blue_26'] = blue_26[0:1827]

In [49]:
df.tail(20)

date  year  index  N1  N2  N3  N4  N5  N6  S1   ...      EvO  \
1807 2017-11-16  2017    134  34  46  40  20   8   3  24   ...     even   
1808 2017-11-18  2017    135  26  24  30  19  41  36  43   ...      odd   
1809 2017-11-21  2017    136   8  36  43  35  27  30  31   ...      odd   
1810 2017-11-23  2017    137   4  37  42  39  30   3  32   ...     even   
1811 2017-11-25  2017    138   5  28  16  40  13  41   2   ...     even   
1812 2017-11-28  2017    139   9  23   6  40  36   8  19   ...      odd   
1813 2017-11-30  2017    140  10  38  47   4  32  35  49   ...      odd   
1814 2017-12-02  2017    141  27  14  38   7  19  28  46   ...     even   
1815 2017-12-05  2017    142  20  44   9  14  18   7  29   ...      odd   
1816 2017-12-07  2017    143  25  39  47  37  34   1  18   ...     even   
1817 2017-12-09  2017    144  22  48  38  24  35  29  30   ...     even   
1818 2017-12-12  2017    145  48  38  15  29  34   4  30   ...     even   
1819 2017-12-14  2017    146   7  34  10  35  25  20   8   ...     even   
1820 2017-12-16  2017    147  24   6   3  28   9   1  36   ...     even   
1821 2017-12-19  2017    148  44  49  38  33   9   3  24   ...     even   
1822 2017-12-21  2017    149  47  30  21  28  14  22   3   ...      odd   
1823 2017-12-24  2017    150  34  39  47   1  16  26  11   ...      odd   
1824 2017-12-26  2017    151  37   2   7  30  16  28  12   ...     even   
1825 2017-12-28  2017    152  46  15  40  44  17  23  11   ...      odd   
1826 2017-12-30  2017    153  13   1  25  38  36  22  37   ...      odd   

         BS month day  red  green  blue  red_26  green_26  blue_26  
1807  small    11  16  627    555   625       6         9       10  
1808    big    11  18  628    555   625       7         8       10  
1809    big    11  21  628    556   625       7         8       10  
1810    big    11  23  628    556   626       7         8       10  
1811  small    11  25  628    557   626       7         9        9  
1812  small    11  28  629    557   626       8         8        9  
1813    big    11  30  630    557   626       9         7        9  
1814    big    12   2  630    558   626       9         7        9  
1815    big    12   5  631    558   626       9         7        9  
1816  small    12   7  632    558   626      10         7        8  
1817    big    12   9  633    558   626      11         6        8  
1818    big    12  12  634    558   626      11         6        8  
1819  small    12  14  635    558   626      12         6        7  
1820    big    12  16  636    558   626      13         6        6  
1821  small    12  19  636    558   627      13         6        6  
1822  small    12  21  637    558   627      14         5        6  
1823  small    12  24  637    558   628      14         4        7  
1824  small    12  26  637    559   628      14         5        6  
1825  small    12  28  638    559   628      15         5        5  
1826    big    12  30  638    560   628      15         6        4  

[20 rows x 22 columns]

In [11]:
df_clean = df[['year','color','red','green','blue','index']]

In [12]:
df_clean.head()

year  color  red  green  blue  index
0  2006   blue    0      0     0      1
1  2006    red    0      0     1      2
2  2006  green    1      0     1      3
3  2006   blue    1      1     1      4
4  2006    red    1      1     2      5

In [13]:
dict_color = {'red':1, 'green':2, 'blue':3}
color = df_clean['color'].map(dict_color)
df_clean.loc[:,'color'] = color

/Users/gznl/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [14]:
# holdout = df_clean[df_clean['year']==2017]
# df_clean = df_clean[df_clean['year']!=2017]
df_clean = df_clean.drop('year', axis=1)

In [15]:
df_clean.tail()

color  red  green  blue  index
1822      3  637    558   627    149
1823      2  637    558   628    150
1824      1  637    559   628    151
1825      2  638    559   628    152
1826      3  638    560   628    153

In [16]:
X = df_clean.drop('color', axis=1)
y = df_clean['color']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [20]:
clf_log = LogisticRegression()
clf_svc = SVC()

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
clf_log.fit(X_train, y_train)
clf_svc.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
score = cross_val_score(clf_log, X_train, y_train, cv=5)
score_svc = cross_val_score(clf_svc, X_train, y_train, cv=5)

In [24]:
print(score)
print(score_svc)

[ 0.39837398  0.36178862  0.35655738  0.35245902  0.4057377 ]
[ 0.34552846  0.29674797  0.34016393  0.32786885  0.38114754]


In [25]:
pred_log = clf_log.predict(X_test)
pred_svc = clf_svc.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
print(confusion_matrix(pred_log, y_test))
print('\n')
print(classification_report(pred_log, y_test))

[[103  86  79]
 [  4   4   4]
 [114  95 114]]


             precision    recall  f1-score   support

          1       0.47      0.38      0.42       268
          2       0.02      0.33      0.04        12
          3       0.58      0.35      0.44       323

avg / total       0.52      0.37      0.42       603



In [28]:
print(confusion_matrix(pred_svc, y_test))
print('\n')
print(classification_report(pred_svc, y_test))

[[70 60 82]
 [60 40 41]
 [91 85 74]]


             precision    recall  f1-score   support

          1       0.32      0.33      0.32       212
          2       0.22      0.28      0.25       141
          3       0.38      0.30      0.33       250

avg / total       0.32      0.31      0.31       603



In [29]:
# X_holdout = holdout[['index','month','day','red','green','blue']]
# y_holdout = holdout['color']

In [30]:
# pred_2017 = clf_log.predict(X_holdout)

In [31]:
# print(confusion_matrix(pred_2017, y_holdout))
# print('\n')
# print(classification_report(pred_2017, y_holdout))

In [32]:
# y_holdout.value_counts()

In [33]:
# import seaborn as sns

In [34]:
# plt.figure(figsize=(12,10))
# sns.countplot(x='year', hue='color', data=df)

In [35]:
df2018_1 = pd.DataFrame({'red':[638],'green':[560],'blue':[629],'index':[1]})
df2018_1.head()

blue  green  index  red
0   629    560      1  638

In [36]:
df2018_2 = pd.DataFrame({'red':[638],'green':[560],'blue':[630],'index':[2]})
df2018_2.head()

blue  green  index  red
0   630    560      2  638

In [38]:
print(clf_svc.predict(df2018_1))


[3]


In [39]:
print(clf_svc.predict(df2018_2))


[3]


In [40]:
df2018_3 = pd.DataFrame({'red':[639],'green':[560],'blue':[630],'index':[3]})
df2018_3.head()

blue  green  index  red
0   630    560      3  639

In [41]:
print(clf_svc.predict(df2018_3))


[3]


In [42]:
pred_svc

array([3, 3, 3, 2, 3, 3, 2, 1, 3, 1, 3, 1, 1, 1, 2, 1, 3, 3, 3, 2, 1, 3, 3,
       1, 2, 1, 1, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2,
       1, 2, 3, 3, 1, 1, 3, 3, 1, 3, 3, 3, 3, 3, 1, 2, 3, 3, 1, 3, 2, 2, 1,
       3, 3, 1, 3, 1, 2, 1, 1, 1, 2, 3, 2, 3, 3, 1, 1, 2, 1, 3, 3, 1, 1, 1,
       3, 2, 2, 2, 2, 2, 3, 3, 3, 1, 3, 2, 3, 3, 1, 1, 2, 3, 1, 1, 2, 1, 1,
       3, 3, 1, 3, 1, 1, 2, 1, 1, 3, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 3, 3,
       3, 1, 1, 1, 1, 1, 3, 3, 2, 1, 3, 3, 1, 1, 2, 3, 3, 3, 3, 3, 3, 1, 3,
       1, 2, 2, 3, 2, 3, 3, 3, 1, 3, 1, 3, 3, 3, 2, 1, 3, 3, 1, 1, 2, 3, 3,
       1, 3, 3, 1, 1, 1, 1, 2, 2, 3, 1, 1, 1, 1, 1, 3, 3, 1, 3, 1, 3, 1, 3,
       1, 3, 2, 1, 1, 3, 3, 3, 1, 3, 1, 2, 2, 1, 3, 3, 1, 1, 3, 1, 2, 2, 3,
       2, 2, 2, 2, 3, 1, 1, 3, 3, 3, 3, 2, 3, 2, 1, 1, 3, 3, 3, 1, 3, 3, 3,
       3, 1, 3, 1, 3, 3, 3, 2, 1, 3, 1, 1, 3, 1, 3, 1, 3, 3, 1, 3, 1, 2, 2,
       2, 1, 3, 3, 1, 1, 1, 2, 2, 1, 2, 3, 2, 3, 2, 1, 1, 3, 2, 2, 3, 2, 2,
       3, 2,