In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('2006_2017_features.csv')

In [3]:
df2006 = df[df['year'] == 2006]

In [4]:
df2006['date'] = pd.to_datetime(df2006['date'])

/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [5]:
df2006.set_index('date', inplace=True)

In [6]:
df2006['day'] = df2006.index.day

/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [7]:
df2006.head()

year  index  N1  N2  N3  N4  N5  N6  S1  color  zodiac   EvO  \
date                                                                       
2006-01-03  2006      1  25  17  38  26  23  24  47   blue     rat   odd   
2006-01-05  2006      2  10  22  46  44   5  38  13    red     dog   odd   
2006-01-08  2006      3  38  26  28  42  10   1  43  green  dragon   odd   
2006-01-10  2006      4  38  39  21  25  36   5   4   blue    goat  even   
2006-01-12  2006      5  15  37  36  24  27  25  35    red     rat   odd   

               BS  month  day  
date                           
2006-01-03    big      1    3  
2006-01-05  small      1    5  
2006-01-08    big      1    8  
2006-01-10  small      1   10  
2006-01-12    big      1   12

In [9]:
df2006.reset_index(drop=True, inplace=True)

In [20]:
df2006_clean = df2006[['index','color','month','day']]

In [27]:
df2006_clean.head()

index  color  month  day
0      1   blue      1    3
1      2    red      1    5
2      3  green      1    8
3      4   blue      1   10
4      5    red      1   12

In [28]:
df2006_clean.shape

(154, 4)

## feature: how many times appears in the past

In [37]:
blue = []
red = []
green = []
for i in range(1,155):
    blue.append(df2006['color'].iloc[:i].value_counts()['blue'])
    
for i in range(2,155):
    red.append(df2006['color'].iloc[:i].value_counts()['red'])
    
for i in range(3,155):
    green.append(df2006['color'].iloc[:i].value_counts()['green'])

blue = [0] + blue
red = [0,0] + red
green = [0,0,0] + green

In [43]:
df2006_clean['red'] = red[0:154]
df2006_clean['green'] = green[0:154]
df2006_clean['blue'] = blue[0:154]

/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the document

In [44]:
df2006_clean.head()

index  color  month  day  red  green  blue
0      1   blue      1    3    0      0     0
1      2    red      1    5    0      0     1
2      3  green      1    8    1      0     1
3      4   blue      1   10    1      1     1
4      5    red      1   12    1      1     2

In [95]:
dict_color = {'red':1, 'green':2, 'blue':3}
color = df2006_clean['color'].map(dict_color)

In [99]:
df2006_clean.drop('color', axis = 1)
df2006_clean['color'] = color

/Users/gznl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [100]:
df2006_clean.tail()

index  color  month  day  red  green  blue
149    150      3     12   19   56     40    53
150    151      2     12   21   56     40    54
151    152      3     12   24   56     41    54
152    153      2     12   28   56     41    55
153    154      3     12   30   56     42    55

## classification 
### feature
* index
* month
* appear times in the past for color red green and blue

### target
* color

In [101]:
X = df2006_clean.drop('color', axis = 1)
y = df2006_clean['color']

In [102]:
from sklearn.model_selection import train_test_split, cross_val_score

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Logisticregression

In [104]:
from sklearn.linear_model import LogisticRegression

In [105]:
clf = LogisticRegression()

In [106]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [107]:
score = cross_val_score(clf, X_train, y_train, cv=5)

In [108]:
print(score)

[ 0.45454545  0.45454545  0.3         0.3         0.42105263]


In [109]:
prediction = clf.predict(X_test)

In [62]:
from sklearn.metrics import confusion_matrix, classification_report

In [110]:
print(confusion_matrix(prediction, y_test))
print('\n')
print(classification_report(prediction, y_test))

[[ 8  2  6]
 [ 2  3  1]
 [ 9 10 10]]


             precision    recall  f1-score   support

          1       0.42      0.50      0.46        16
          2       0.20      0.50      0.29         6
          3       0.59      0.34      0.43        29

avg / total       0.49      0.41      0.42        51



## SVM

In [71]:
from sklearn.svm import SVC

In [72]:
from sklearn.model_selection import GridSearchCV

In [111]:
clf_svc = SVC()

In [112]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [114]:
grid = GridSearchCV(clf_svc,param_grid)

In [115]:
grid.fit(X_train, y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [116]:
grid.best_params_

{'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

In [117]:
grid.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [118]:
grid_predictions = grid.predict(X_test)

In [119]:
print(confusion_matrix(grid_predictions, y_test))
print('\n')
print(classification_report(grid_predictions, y_test))

[[ 7  3  8]
 [ 2  1  2]
 [10 11  7]]


             precision    recall  f1-score   support

          1       0.37      0.39      0.38        18
          2       0.07      0.20      0.10         5
          3       0.41      0.25      0.31        28

avg / total       0.36      0.29      0.31        51



## Random forest

In [120]:
from sklearn.ensemble import RandomForestClassifier

In [122]:
rfc = RandomForestClassifier(n_estimators=10)

In [123]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [124]:
score = cross_val_score(rfc, X_train, y_train, cv=5)

In [125]:
print(score)

[ 0.45454545  0.36363636  0.4         0.25        0.31578947]


In [126]:
rf_prediction = rfc.predict(X_test)

In [127]:
print(confusion_matrix(rf_prediction, y_test))
print('\n')
print(classification_report(rf_prediction, y_test))

[[ 8  3  8]
 [ 4  2  3]
 [ 7 10  6]]


             precision    recall  f1-score   support

          1       0.42      0.42      0.42        19
          2       0.13      0.22      0.17         9
          3       0.35      0.26      0.30        23

avg / total       0.34      0.31      0.32        51



## It seems logisticregression outperform other two models based on only one year 2006 data. Next step will be on 10 year data.